### ISSUE TITLE
Fix `devtools:check()` warnings and notes

### ISSUE THREAD

**Issue by sims1253** [sims1253/bayesfam#1]

**Comment by Yannick73** [comment]
Also correct spelling mistakes found by devtools::spell_check()

**Comment by Yannick73** [comment]
Spelling mistakes corrected. Examples in check still fail though. Not sure why. But all examples checked by hand, seem to work alright.

**Comment by Yannick73** [comment]
Done now. All remaining example errors fixed and pushed to bugfixing branch.
